spring:
  application:
    name: clean-architecture
  data:
    mongodb:
      uri: "mongodb://clean:clean@localhost:27017/clean-arch?authSource=admin"
  datasource:
    url: jdbc:postgresql://localhost:15432/clean-arch
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqp://localhost:5672
    username: rabbitmq
    password: rabbitmq

encontro:
  broker:
    exchange:
      produtoEventExchange: encontro.produtoevent
    queue:
      produtoEventQueue:
        name: encontro.produtoevent
